[package]
name = "liberum_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
liberum_core = { path = "../liberum_core"}
clap = {version="4", features=["cargo", "derive"]}
clap_derive = {version="4"}
shlex = "1"
homedir = "0.3"
tokio ={ version = "1.40", features = ["full"]}